version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Jakarta"
    assignees:
      - "ray-1337"
    commit-message:
      include: "scope"
      prefix: ""
    target-branch: "nefertiti"
    versioning-strategy: "increase"
    labels:
      - "dependencies"
